namespace MarketScanner.Core.Models;

/// <summary>
/// Describes the activation of a configured trigger during a scan. Generated by analytics engines and consumed by downstream workflows.
/// </summary>
public record TriggerHit
{
    /// <summary>
    /// Gets the name of the trigger responsible for the hit.
    /// </summary>
    public string TriggerName { get; init; } = string.Empty;

    /// <summary>
    /// Gets a descriptive message explaining why the trigger fired.
    /// </summary>
    public string Description { get; init; } = string.Empty;

    /// <summary>
    /// Gets the point in time when the trigger fired.
    /// </summary>
    public DateTimeOffset OccurredAt { get; init; }
}
